/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GenericErrorModel,
  ProfileResponse
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get a profile of a user of the system. Auth is optional
 * @summary Get a profile
 */
export const getProfileByUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileResponse>> => {
    
    
    return axios.get(
      `http://localhost:3000/api/profiles/${username}`,options
    );
  }




export const getGetProfileByUsernameQueryKey = (username?: string,) => {
    return [
    `http://localhost:3000/api/profiles/${username}`
    ] as const;
    }

    
export const getGetProfileByUsernameQueryOptions = <TData = Awaited<ReturnType<typeof getProfileByUsername>>, TError = AxiosError<void | GenericErrorModel>>(username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileByUsernameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfileByUsername>>> = ({ signal }) => getProfileByUsername(username, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProfileByUsernameQueryResult = NonNullable<Awaited<ReturnType<typeof getProfileByUsername>>>
export type GetProfileByUsernameQueryError = AxiosError<void | GenericErrorModel>


export function useGetProfileByUsername<TData = Awaited<ReturnType<typeof getProfileByUsername>>, TError = AxiosError<void | GenericErrorModel>>(
 username: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileByUsername>>,
          TError,
          Awaited<ReturnType<typeof getProfileByUsername>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileByUsername<TData = Awaited<ReturnType<typeof getProfileByUsername>>, TError = AxiosError<void | GenericErrorModel>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProfileByUsername>>,
          TError,
          Awaited<ReturnType<typeof getProfileByUsername>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProfileByUsername<TData = Awaited<ReturnType<typeof getProfileByUsername>>, TError = AxiosError<void | GenericErrorModel>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a profile
 */

export function useGetProfileByUsername<TData = Awaited<ReturnType<typeof getProfileByUsername>>, TError = AxiosError<void | GenericErrorModel>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProfileByUsername>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProfileByUsernameQueryOptions(username,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Follow a user by username
 * @summary Follow a user
 */
export const followUserByUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileResponse>> => {
    
    
    return axios.post(
      `http://localhost:3000/api/profiles/${username}/follow`,undefined,options
    );
  }



export const getFollowUserByUsernameMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof followUserByUsername>>, TError,{username: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof followUserByUsername>>, TError,{username: string}, TContext> => {

const mutationKey = ['followUserByUsername'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof followUserByUsername>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  followUserByUsername(username,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FollowUserByUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof followUserByUsername>>>
    
    export type FollowUserByUsernameMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Follow a user
 */
export const useFollowUserByUsername = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof followUserByUsername>>, TError,{username: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof followUserByUsername>>,
        TError,
        {username: string},
        TContext
      > => {

      const mutationOptions = getFollowUserByUsernameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unfollow a user by username
 * @summary Unfollow a user
 */
export const unfollowUserByUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileResponse>> => {
    
    
    return axios.delete(
      `http://localhost:3000/api/profiles/${username}/follow`,options
    );
  }



export const getUnfollowUserByUsernameMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfollowUserByUsername>>, TError,{username: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unfollowUserByUsername>>, TError,{username: string}, TContext> => {

const mutationKey = ['unfollowUserByUsername'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unfollowUserByUsername>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  unfollowUserByUsername(username,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnfollowUserByUsernameMutationResult = NonNullable<Awaited<ReturnType<typeof unfollowUserByUsername>>>
    
    export type UnfollowUserByUsernameMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Unfollow a user
 */
export const useUnfollowUserByUsername = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unfollowUserByUsername>>, TError,{username: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unfollowUserByUsername>>,
        TError,
        {username: string},
        TContext
      > => {

      const mutationOptions = getUnfollowUserByUsernameMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    