/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ProfileResponse
} from '.././model';


export const getGetProfileByUsernameResponseMock = (overrideResponse: Partial< ProfileResponse > = {}): ProfileResponse => ({profile: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}, ...overrideResponse})

export const getFollowUserByUsernameResponseMock = (overrideResponse: Partial< ProfileResponse > = {}): ProfileResponse => ({profile: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}, ...overrideResponse})

export const getUnfollowUserByUsernameResponseMock = (overrideResponse: Partial< ProfileResponse > = {}): ProfileResponse => ({profile: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}, ...overrideResponse})


export const getGetProfileByUsernameMockHandler = (overrideResponse?: ProfileResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProfileResponse> | ProfileResponse), options?: RequestHandlerOptions) => {
  return http.get('*/profiles/:username', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProfileByUsernameResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getFollowUserByUsernameMockHandler = (overrideResponse?: ProfileResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ProfileResponse> | ProfileResponse), options?: RequestHandlerOptions) => {
  return http.post('*/profiles/:username/follow', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFollowUserByUsernameResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUnfollowUserByUsernameMockHandler = (overrideResponse?: ProfileResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<ProfileResponse> | ProfileResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/profiles/:username/follow', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUnfollowUserByUsernameResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getProfileMock = () => [
  getGetProfileByUsernameMockHandler(),
  getFollowUserByUsernameMockHandler(),
  getUnfollowUserByUsernameMockHandler()
]
