/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  UserResponse
} from '.././model';


export const getLoginResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({user: {email: faker.string.alpha({length: {min: 10, max: 20}}), token: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getCreateUserResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({user: {email: faker.string.alpha({length: {min: 10, max: 20}}), token: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getGetCurrentUserResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({user: {email: faker.string.alpha({length: {min: 10, max: 20}}), token: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})

export const getUpdateCurrentUserResponseMock = (overrideResponse: Partial< UserResponse > = {}): UserResponse => ({user: {email: faker.string.alpha({length: {min: 10, max: 20}}), token: faker.string.alpha({length: {min: 10, max: 20}}), username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}})}, ...overrideResponse})


export const getLoginMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.post('*/users/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateUserMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.post('*/users', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateUserResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetCurrentUserMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.get('*/user', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCurrentUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateCurrentUserMockHandler = (overrideResponse?: UserResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UserResponse> | UserResponse), options?: RequestHandlerOptions) => {
  return http.put('*/user', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateCurrentUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUserAndAuthenticationMock = () => [
  getLoginMockHandler(),
  getCreateUserMockHandler(),
  getGetCurrentUserMockHandler(),
  getUpdateCurrentUserMockHandler()
]
