/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GenericErrorModel,
  GetArticlesFeedParams,
  GetArticlesParams,
  MultipleArticlesResponse,
  NewArticleRequest,
  SingleArticleResponse,
  UpdateArticleRequest
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get most recent articles from users you follow. Use query parameters to limit. Auth is required
 * @summary Get recent articles from users you follow
 */
export const getArticlesFeed = (
    params?: GetArticlesFeedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MultipleArticlesResponse>> => {
    
    
    return axios.get(
      `http://localhost:3000/api/articles/feed`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetArticlesFeedQueryKey = (params?: GetArticlesFeedParams,) => {
    return [
    `http://localhost:3000/api/articles/feed`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetArticlesFeedQueryOptions = <TData = Awaited<ReturnType<typeof getArticlesFeed>>, TError = AxiosError<void | GenericErrorModel>>(params?: GetArticlesFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticlesFeedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticlesFeed>>> = ({ signal }) => getArticlesFeed(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArticlesFeedQueryResult = NonNullable<Awaited<ReturnType<typeof getArticlesFeed>>>
export type GetArticlesFeedQueryError = AxiosError<void | GenericErrorModel>


export function useGetArticlesFeed<TData = Awaited<ReturnType<typeof getArticlesFeed>>, TError = AxiosError<void | GenericErrorModel>>(
 params: undefined |  GetArticlesFeedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticlesFeed>>,
          TError,
          Awaited<ReturnType<typeof getArticlesFeed>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticlesFeed<TData = Awaited<ReturnType<typeof getArticlesFeed>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticlesFeed>>,
          TError,
          Awaited<ReturnType<typeof getArticlesFeed>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticlesFeed<TData = Awaited<ReturnType<typeof getArticlesFeed>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recent articles from users you follow
 */

export function useGetArticlesFeed<TData = Awaited<ReturnType<typeof getArticlesFeed>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesFeedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticlesFeed>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetArticlesFeedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get most recent articles globally. Use query parameters to filter results. Auth is optional
 * @summary Get recent articles globally
 */
export const getArticles = (
    params?: GetArticlesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MultipleArticlesResponse>> => {
    
    
    return axios.get(
      `http://localhost:3000/api/articles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetArticlesQueryKey = (params?: GetArticlesParams,) => {
    return [
    `http://localhost:3000/api/articles`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetArticlesQueryOptions = <TData = Awaited<ReturnType<typeof getArticles>>, TError = AxiosError<void | GenericErrorModel>>(params?: GetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticlesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticles>>> = ({ signal }) => getArticles(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof getArticles>>>
export type GetArticlesQueryError = AxiosError<void | GenericErrorModel>


export function useGetArticles<TData = Awaited<ReturnType<typeof getArticles>>, TError = AxiosError<void | GenericErrorModel>>(
 params: undefined |  GetArticlesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticles>>,
          TError,
          Awaited<ReturnType<typeof getArticles>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticles<TData = Awaited<ReturnType<typeof getArticles>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticles>>,
          TError,
          Awaited<ReturnType<typeof getArticles>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticles<TData = Awaited<ReturnType<typeof getArticles>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recent articles globally
 */

export function useGetArticles<TData = Awaited<ReturnType<typeof getArticles>>, TError = AxiosError<void | GenericErrorModel>>(
 params?: GetArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticles>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetArticlesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create an article. Auth is required
 * @summary Create an article
 */
export const createArticle = (
    newArticleRequest: NewArticleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleArticleResponse>> => {
    
    
    return axios.post(
      `http://localhost:3000/api/articles`,
      newArticleRequest,options
    );
  }



export const getCreateArticleMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: NewArticleRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: NewArticleRequest}, TContext> => {

const mutationKey = ['createArticle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createArticle>>, {data: NewArticleRequest}> = (props) => {
          const {data} = props ?? {};

          return  createArticle(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateArticleMutationResult = NonNullable<Awaited<ReturnType<typeof createArticle>>>
    export type CreateArticleMutationBody = NewArticleRequest
    export type CreateArticleMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Create an article
 */
export const useCreateArticle = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: NewArticleRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createArticle>>,
        TError,
        {data: NewArticleRequest},
        TContext
      > => {

      const mutationOptions = getCreateArticleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get an article. Auth not required
 * @summary Get an article
 */
export const getArticle = (
    slug: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleArticleResponse>> => {
    
    
    return axios.get(
      `http://localhost:3000/api/articles/${slug}`,options
    );
  }




export const getGetArticleQueryKey = (slug?: string,) => {
    return [
    `http://localhost:3000/api/articles/${slug}`
    ] as const;
    }

    
export const getGetArticleQueryOptions = <TData = Awaited<ReturnType<typeof getArticle>>, TError = AxiosError<GenericErrorModel>>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticleQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticle>>> = ({ signal }) => getArticle(slug, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArticleQueryResult = NonNullable<Awaited<ReturnType<typeof getArticle>>>
export type GetArticleQueryError = AxiosError<GenericErrorModel>


export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = AxiosError<GenericErrorModel>>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticle>>,
          TError,
          Awaited<ReturnType<typeof getArticle>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = AxiosError<GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticle>>,
          TError,
          Awaited<ReturnType<typeof getArticle>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = AxiosError<GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an article
 */

export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = AxiosError<GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetArticleQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update an article. Auth is required
 * @summary Update an article
 */
export const updateArticle = (
    slug: string,
    updateArticleRequest: UpdateArticleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleArticleResponse>> => {
    
    
    return axios.put(
      `http://localhost:3000/api/articles/${slug}`,
      updateArticleRequest,options
    );
  }



export const getUpdateArticleMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{slug: string;data: UpdateArticleRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{slug: string;data: UpdateArticleRequest}, TContext> => {

const mutationKey = ['updateArticle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateArticle>>, {slug: string;data: UpdateArticleRequest}> = (props) => {
          const {slug,data} = props ?? {};

          return  updateArticle(slug,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateArticleMutationResult = NonNullable<Awaited<ReturnType<typeof updateArticle>>>
    export type UpdateArticleMutationBody = UpdateArticleRequest
    export type UpdateArticleMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Update an article
 */
export const useUpdateArticle = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{slug: string;data: UpdateArticleRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateArticle>>,
        TError,
        {slug: string;data: UpdateArticleRequest},
        TContext
      > => {

      const mutationOptions = getUpdateArticleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete an article. Auth is required
 * @summary Delete an article
 */
export const deleteArticle = (
    slug: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `http://localhost:3000/api/articles/${slug}`,options
    );
  }



export const getDeleteArticleMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteArticle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteArticle>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteArticle(slug,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteArticleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteArticle>>>
    
    export type DeleteArticleMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Delete an article
 */
export const useDeleteArticle = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteArticle>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getDeleteArticleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    