/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MultipleArticlesResponse,
  SingleArticleResponse
} from '.././model';


export const getGetArticlesFeedResponseMock = (overrideResponse: Partial< MultipleArticlesResponse > = {}): MultipleArticlesResponse => ({articles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}})), articlesCount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetArticlesResponseMock = (overrideResponse: Partial< MultipleArticlesResponse > = {}): MultipleArticlesResponse => ({articles: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}})), articlesCount: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getCreateArticleResponseMock = (overrideResponse: Partial< SingleArticleResponse > = {}): SingleArticleResponse => ({article: {slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})

export const getGetArticleResponseMock = (overrideResponse: Partial< SingleArticleResponse > = {}): SingleArticleResponse => ({article: {slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})

export const getUpdateArticleResponseMock = (overrideResponse: Partial< SingleArticleResponse > = {}): SingleArticleResponse => ({article: {slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})


export const getGetArticlesFeedMockHandler = (overrideResponse?: MultipleArticlesResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MultipleArticlesResponse> | MultipleArticlesResponse), options?: RequestHandlerOptions) => {
  return http.get('*/articles/feed', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticlesFeedResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetArticlesMockHandler = (overrideResponse?: MultipleArticlesResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MultipleArticlesResponse> | MultipleArticlesResponse), options?: RequestHandlerOptions) => {
  return http.get('*/articles', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticlesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateArticleMockHandler = (overrideResponse?: SingleArticleResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SingleArticleResponse> | SingleArticleResponse), options?: RequestHandlerOptions) => {
  return http.post('*/articles', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateArticleResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetArticleMockHandler = (overrideResponse?: SingleArticleResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<SingleArticleResponse> | SingleArticleResponse), options?: RequestHandlerOptions) => {
  return http.get('*/articles/:slug', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateArticleMockHandler = (overrideResponse?: SingleArticleResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<SingleArticleResponse> | SingleArticleResponse), options?: RequestHandlerOptions) => {
  return http.put('*/articles/:slug', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateArticleResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteArticleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/articles/:slug', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getArticlesMock = () => [
  getGetArticlesFeedMockHandler(),
  getGetArticlesMockHandler(),
  getCreateArticleMockHandler(),
  getGetArticleMockHandler(),
  getUpdateArticleMockHandler(),
  getDeleteArticleMockHandler()
]
