/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GenericErrorModel,
  MultipleCommentsResponse,
  NewCommentRequest,
  SingleCommentResponse
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Get the comments for an article. Auth is optional
 * @summary Get comments for an article
 */
export const getArticleComments = (
    slug: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MultipleCommentsResponse>> => {
    
    
    return axios.get(
      `http://localhost:3000/api/articles/${slug}/comments`,options
    );
  }




export const getGetArticleCommentsQueryKey = (slug?: string,) => {
    return [
    `http://localhost:3000/api/articles/${slug}/comments`
    ] as const;
    }

    
export const getGetArticleCommentsQueryOptions = <TData = Awaited<ReturnType<typeof getArticleComments>>, TError = AxiosError<void | GenericErrorModel>>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticleCommentsQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticleComments>>> = ({ signal }) => getArticleComments(slug, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArticleCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof getArticleComments>>>
export type GetArticleCommentsQueryError = AxiosError<void | GenericErrorModel>


export function useGetArticleComments<TData = Awaited<ReturnType<typeof getArticleComments>>, TError = AxiosError<void | GenericErrorModel>>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticleComments>>,
          TError,
          Awaited<ReturnType<typeof getArticleComments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticleComments<TData = Awaited<ReturnType<typeof getArticleComments>>, TError = AxiosError<void | GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticleComments>>,
          TError,
          Awaited<ReturnType<typeof getArticleComments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticleComments<TData = Awaited<ReturnType<typeof getArticleComments>>, TError = AxiosError<void | GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get comments for an article
 */

export function useGetArticleComments<TData = Awaited<ReturnType<typeof getArticleComments>>, TError = AxiosError<void | GenericErrorModel>>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticleComments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetArticleCommentsQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a comment for an article. Auth is required
 * @summary Create a comment for an article
 */
export const createArticleComment = (
    slug: string,
    newCommentRequest: NewCommentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleCommentResponse>> => {
    
    
    return axios.post(
      `http://localhost:3000/api/articles/${slug}/comments`,
      newCommentRequest,options
    );
  }



export const getCreateArticleCommentMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticleComment>>, TError,{slug: string;data: NewCommentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createArticleComment>>, TError,{slug: string;data: NewCommentRequest}, TContext> => {

const mutationKey = ['createArticleComment'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createArticleComment>>, {slug: string;data: NewCommentRequest}> = (props) => {
          const {slug,data} = props ?? {};

          return  createArticleComment(slug,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateArticleCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createArticleComment>>>
    export type CreateArticleCommentMutationBody = NewCommentRequest
    export type CreateArticleCommentMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Create a comment for an article
 */
export const useCreateArticleComment = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticleComment>>, TError,{slug: string;data: NewCommentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createArticleComment>>,
        TError,
        {slug: string;data: NewCommentRequest},
        TContext
      > => {

      const mutationOptions = getCreateArticleCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a comment for an article. Auth is required
 * @summary Delete a comment for an article
 */
export const deleteArticleComment = (
    slug: string,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `http://localhost:3000/api/articles/${slug}/comments/${id}`,options
    );
  }



export const getDeleteArticleCommentMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticleComment>>, TError,{slug: string;id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteArticleComment>>, TError,{slug: string;id: number}, TContext> => {

const mutationKey = ['deleteArticleComment'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteArticleComment>>, {slug: string;id: number}> = (props) => {
          const {slug,id} = props ?? {};

          return  deleteArticleComment(slug,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteArticleCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteArticleComment>>>
    
    export type DeleteArticleCommentMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Delete a comment for an article
 */
export const useDeleteArticleComment = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticleComment>>, TError,{slug: string;id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteArticleComment>>,
        TError,
        {slug: string;id: number},
        TContext
      > => {

      const mutationOptions = getDeleteArticleCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    