/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MultipleCommentsResponse,
  SingleCommentResponse
} from '.././model';


export const getGetArticleCommentsResponseMock = (overrideResponse: Partial< MultipleCommentsResponse > = {}): MultipleCommentsResponse => ({comments: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, body: faker.string.alpha({length: {min: 10, max: 20}}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}})), ...overrideResponse})

export const getCreateArticleCommentResponseMock = (overrideResponse: Partial< SingleCommentResponse > = {}): SingleCommentResponse => ({comment: {id: faker.number.int({min: undefined, max: undefined}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, body: faker.string.alpha({length: {min: 10, max: 20}}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})


export const getGetArticleCommentsMockHandler = (overrideResponse?: MultipleCommentsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MultipleCommentsResponse> | MultipleCommentsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/articles/:slug/comments', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetArticleCommentsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateArticleCommentMockHandler = (overrideResponse?: SingleCommentResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SingleCommentResponse> | SingleCommentResponse), options?: RequestHandlerOptions) => {
  return http.post('*/articles/:slug/comments', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateArticleCommentResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteArticleCommentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/articles/:slug/comments/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getCommentsMock = () => [
  getGetArticleCommentsMockHandler(),
  getCreateArticleCommentMockHandler(),
  getDeleteArticleCommentMockHandler()
]
