/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  SingleArticleResponse
} from '.././model';


export const getCreateArticleFavoriteResponseMock = (overrideResponse: Partial< SingleArticleResponse > = {}): SingleArticleResponse => ({article: {slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})

export const getDeleteArticleFavoriteResponseMock = (overrideResponse: Partial< SingleArticleResponse > = {}): SingleArticleResponse => ({article: {slug: faker.string.alpha({length: {min: 10, max: 20}}), title: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.string.alpha({length: {min: 10, max: 20}}), body: faker.string.alpha({length: {min: 10, max: 20}}), tagList: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`, favorited: faker.datatype.boolean(), favoritesCount: faker.number.int({min: undefined, max: undefined}), author: {username: faker.string.alpha({length: {min: 10, max: 20}}), bio: faker.string.alpha({length: {min: 10, max: 20}}), image: faker.string.alpha({length: {min: 10, max: 20}}), following: faker.datatype.boolean()}}, ...overrideResponse})


export const getCreateArticleFavoriteMockHandler = (overrideResponse?: SingleArticleResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SingleArticleResponse> | SingleArticleResponse), options?: RequestHandlerOptions) => {
  return http.post('*/articles/:slug/favorite', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateArticleFavoriteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteArticleFavoriteMockHandler = (overrideResponse?: SingleArticleResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<SingleArticleResponse> | SingleArticleResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/articles/:slug/favorite', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteArticleFavoriteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getFavoritesMock = () => [
  getCreateArticleFavoriteMockHandler(),
  getDeleteArticleFavoriteMockHandler()
]
