/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GenericErrorModel,
  SingleArticleResponse
} from '.././model';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Favorite an article. Auth is required
 * @summary Favorite an article
 */
export const createArticleFavorite = (
    slug: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleArticleResponse>> => {
    
    
    return axios.post(
      `http://localhost:3000/api/articles/${slug}/favorite`,undefined,options
    );
  }



export const getCreateArticleFavoriteMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticleFavorite>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createArticleFavorite>>, TError,{slug: string}, TContext> => {

const mutationKey = ['createArticleFavorite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createArticleFavorite>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  createArticleFavorite(slug,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateArticleFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof createArticleFavorite>>>
    
    export type CreateArticleFavoriteMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Favorite an article
 */
export const useCreateArticleFavorite = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticleFavorite>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createArticleFavorite>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getCreateArticleFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unfavorite an article. Auth is required
 * @summary Unfavorite an article
 */
export const deleteArticleFavorite = (
    slug: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SingleArticleResponse>> => {
    
    
    return axios.delete(
      `http://localhost:3000/api/articles/${slug}/favorite`,options
    );
  }



export const getDeleteArticleFavoriteMutationOptions = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticleFavorite>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteArticleFavorite>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteArticleFavorite'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteArticleFavorite>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteArticleFavorite(slug,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteArticleFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteArticleFavorite>>>
    
    export type DeleteArticleFavoriteMutationError = AxiosError<void | GenericErrorModel>

    /**
 * @summary Unfavorite an article
 */
export const useDeleteArticleFavorite = <TError = AxiosError<void | GenericErrorModel>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticleFavorite>>, TError,{slug: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteArticleFavorite>>,
        TError,
        {slug: string},
        TContext
      > => {

      const mutationOptions = getDeleteArticleFavoriteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    