/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import type { NewUser } from './newUser';

export interface NewUserRequest {
  user: NewUser;
}
