/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUser {
  email?: string;
  token?: string;
  username?: string;
  bio?: string;
  image?: string;
}
