/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Conduit API
 * Conduit API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TagsResponse
} from '.././model';


export const getGetTagsResponseMock = (overrideResponse: Partial< TagsResponse > = {}): TagsResponse => ({tags: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), ...overrideResponse})


export const getGetTagsMockHandler = (overrideResponse?: TagsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TagsResponse> | TagsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/tags', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTagsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getDefaultMock = () => [
  getGetTagsMockHandler()
]
